name: Test & Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EgorDm/gha-yarn-node-cache@v1
      
      - name: Install dependencies
        run: yarn install
      
      - name: Install dependencies
        run: yarn build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EgorDm/gha-yarn-node-cache@v1
      
      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
      
      
